In [ ]:
# pip install fuzzywuzzy
# pip install python-Levenshtein

In [108]:
import pandas as pd
from fuzzywuzzy import fuzz

In [80]:
df_raw=pd.read_csv('inputs/Vocabulearn_all.csv')

In [81]:
#Fonction de filtre globale
def remove_punctuation(text):
    special_punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for ele in text:
        if ele in special_punc:
            text = text.replace(ele, " ")
    return text
langues=list(set(list(df_global.columns))-set(['ID','ENGLISH_stem','OCCURENCES','INTERVAL']))
def process_global(df):
    df['INTERVAL']=pd.qcut(df['OCCURENCES'],100,duplicates='drop',labels=False)
    df['INTERVAL']=100-df['INTERVAL']
    for column in langues:
        df[column]=df[column].apply(remove_punctuation)
    return df
df_global=process_global(df_raw)

In [82]:
#Split en plusieurs dataset
dicte_langue={}
for langue in langues:
    dicte_langue[langue]=df_global[['ID',langue]]
df_interval=df_global[['ID','INTERVAL']]

In [83]:
#Filtre de chaque dataset selon son type
def filtre_langue(df,langue):
    df['_len']=df[langue].apply(len)
    df=df[(df['_len']>3)&(df['_len']<13)]
    df=df.drop(columns=['_len'])
    return df
for langue in langues:
    dicte_langue[langue]=filtre_langue(dicte_langue[langue],langue)

<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)
<ipython-input-83-56c711d5fbd5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['_len']=df[langue].apply(len)

In [84]:
langues_bizarre=['CHINESE','KOREAN','JAPAN','RUSSIAN','ARABE']
def filtre_langue_bizarre(df,langue):
    def filter_latin(text):
        text=text.lower()
        alphabet="abcdefghijklmnopqrstvwxyzéèêìîï"
        for letter in alphabet:
            if letter in text:
                return False
        return True
    df['_contain_latin']=df[langue].apply(filter_latin)
    df=df[df['_contain_latin']]
    df=df.drop(columns=['_contain_latin'])
    return df
for langue in langues_bizarre:
    dicte_langue[langue]=filtre_langue_bizarre(dicte_langue[langue],langue)

In [95]:
#Filtre post-selection

In [137]:
def merge_and_filter(speak,learn):
    speak_df=dicte_langue[speak]
    learn_df=dicte_langue[learn]
    df=speak_df.merge(learn_df, how='inner', on='ID')
    df=df.merge(df_interval, how='inner', on='ID')
    df['_is_egal']=df[speak]==df[learn]
    df=df[~df['_is_egal']]
    df['_fuzzy_ratio'] = df.apply(lambda x: fuzz.ratio(x[speak], x[learn]), axis=1)
    df=df[df['_fuzzy_ratio']<70]
    df=df.drop(columns=['_is_egal','_fuzzy_ratio'])
    return df

In [154]:
for langue_speak in langues:
    langues2=[langue for langue in langues if langue!=langue_speak]
    for langue_learn in langues2:
        df=merge_and_filter(langue_speak,langue_learn)
        print(langue_speak,langue_learn,len(df))

ENGLISH CHINESE 1232
ENGLISH KOREAN 3609
ENGLISH JAPAN 5045
ENGLISH FRENCH 5333
ENGLISH HINDI 10584
ENGLISH DEUTSCH 6365
ENGLISH SPAIN 5741
ENGLISH POLONAIS 7152
ENGLISH TURC 7012
ENGLISH RUSSIAN 10486
ENGLISH ARABE 9749
ENGLISH DANOIS 4852
CHINESE ENGLISH 1232
CHINESE KOREAN 864
CHINESE JAPAN 881
CHINESE FRENCH 1162
CHINESE HINDI 1180
CHINESE DEUTSCH 1119
CHINESE SPAIN 1145
CHINESE POLONAIS 1130
CHINESE TURC 1176
CHINESE RUSSIAN 1072
CHINESE ARABE 1044
CHINESE DANOIS 1188
KOREAN ENGLISH 3609
KOREAN CHINESE 864
KOREAN JAPAN 2166
KOREAN FRENCH 3376
KOREAN HINDI 3328
KOREAN DEUTSCH 3362
KOREAN SPAIN 3349
KOREAN POLONAIS 3326
KOREAN TURC 3443
KOREAN RUSSIAN 3087
KOREAN ARABE 2971
KOREAN DANOIS 3516
JAPAN ENGLISH 5045
JAPAN CHINESE 881
JAPAN KOREAN 2166
JAPAN FRENCH 4811
JAPAN HINDI 4678
JAPAN DEUTSCH 4835
JAPAN SPAIN 4783
JAPAN POLONAIS 4803
JAPAN TURC 4849
JAPAN RUSSIAN 4420
JAPAN ARABE 4153
JAPAN DANOIS 4958
FRENCH ENGLISH 5323
FRENCH CHINESE 1162
FRENCH KOREAN 3376
FRENCH JAPAN 4811
FRENCH HINDI 10283
FRENCH DEUTSCH 7387
FRENCH SPAIN 6179
FRENCH POLONAIS 7904
FRENCH TURC 7645
FRENCH RUSSIAN 10232
FRENCH ARABE 9381
FRENCH DANOIS 7132
HINDI ENGLISH 10584
HINDI CHINESE 1180
HINDI KOREAN 3328
HINDI JAPAN 4678
HINDI FRENCH 10283
HINDI DEUTSCH 10375
HINDI SPAIN 10282
HINDI POLONAIS 10287
HINDI TURC 10294
HINDI RUSSIAN 9608
HINDI ARABE 9048
HINDI DANOIS 10556
DEUTSCH ENGLISH 6364
DEUTSCH CHINESE 1119
DEUTSCH KOREAN 3362
DEUTSCH JAPAN 4835
DEUTSCH FRENCH 7393
DEUTSCH HINDI 10375
DEUTSCH SPAIN 7981
DEUTSCH POLONAIS 7758
DEUTSCH TURC 7862
DEUTSCH RUSSIAN 10293
DEUTSCH ARABE 9439
DEUTSCH DANOIS 6406
SPAIN ENGLISH 5739
SPAIN CHINESE 1145
SPAIN KOREAN 3349
SPAIN JAPAN 4783
SPAIN FRENCH 6178
SPAIN HINDI 10282
SPAIN DEUTSCH 7980
SPAIN POLONAIS 7729
SPAIN TURC 7736
SPAIN RUSSIAN 10218
SPAIN ARABE 9369
SPAIN DANOIS 7608
POLONAIS ENGLISH 7153
POLONAIS CHINESE 1130
POLONAIS KOREAN 3326
POLONAIS JAPAN 4803
POLONAIS FRENCH 7906
POLONAIS HINDI 10287
POLONAIS DEUTSCH 7757
POLONAIS SPAIN 7729
POLONAIS TURC 7739
POLONAIS RUSSIAN 10292
POLONAIS ARABE 9333
POLONAIS DANOIS 7210
TURC ENGLISH 7011
TURC CHINESE 1176
TURC KOREAN 3443
TURC JAPAN 4849
TURC FRENCH 7646
TURC HINDI 10294
TURC DEUTSCH 7862
TURC SPAIN 7736
TURC POLONAIS 7742
TURC RUSSIAN 10118
TURC ARABE 9400
TURC DANOIS 7429
RUSSIAN ENGLISH 10486
RUSSIAN CHINESE 1072
RUSSIAN KOREAN 3087
RUSSIAN JAPAN 4420
RUSSIAN FRENCH 10232
RUSSIAN HINDI 9608
RUSSIAN DEUTSCH 10293
RUSSIAN SPAIN 10218
RUSSIAN POLONAIS 10292
RUSSIAN TURC 10118
RUSSIAN ARABE 8730
RUSSIAN DANOIS 10397
ARABE ENGLISH 9749
ARABE CHINESE 1044
ARABE KOREAN 2971
ARABE JAPAN 4153
ARABE FRENCH 9381
ARABE HINDI 9048
ARABE DEUTSCH 9439
ARABE SPAIN 9369
ARABE POLONAIS 9333
ARABE TURC 9400
ARABE RUSSIAN 8730
ARABE DANOIS 9586
DANOIS ENGLISH 4853
DANOIS CHINESE 1188
DANOIS KOREAN 3516
DANOIS JAPAN 4958
DANOIS FRENCH 7144
DANOIS HINDI 10556
DANOIS DEUTSCH 6406
DANOIS SPAIN 7609
DANOIS POLONAIS 7210
DANOIS TURC 7429
DANOIS RUSSIAN 10397
DANOIS ARABE 9586

In [138]:
df=merge_and_filter(speak,learn)

In [139]:
df.

          ID        FRENCH    ENGLISH  INTERVAL
0          1  intention de    intents       100
4          5     thermique      thule       100
6          7     trébucher    stumble       100
9         10      remonter     remade       100
13        17      maniaque      manic       100
...      ...           ...        ...       ...
11573  13785         petit      small         5
11574  13786       Zélande    zealand         5
11575  13787  Par ailleurs  otherwise         5
11576  13788         décès      death         5
11577  13789       Analyse   analysis         5

[5323 rows x 4 columns]

In [102]:
df

          ID        FRENCH     ENGLISH  INTERVAL
0          1  intention de     intents       100
1          2    pipéridine  piperidine       100
2          3       bretzel     pretzel       100
3          4       amorphe   amorphous       100
4          5     thermique       thule       100
...      ...           ...         ...       ...
11574  13786       Zélande     zealand         5
11575  13787  Par ailleurs   otherwise         5
11576  13788         décès       death         5
11577  13789       Analyse    analysis         5
11578  13791    télévision  television         5

[8797 rows x 4 columns]